- hosts: ogd_raspberries
  become: true
  handlers:
    - include: handlers/noop.yml
  roles:
    - name: raspi-config
      tags: raspi-config
    - name: fstrim
      tags: fstrim
    - name: persistent-journal
      tags: persistent-journal
    - name: libseccomp2
      tags: libseccomp2
    - name: update
      tags: update
    - name: tools
      tags: tools
    - name: dotfiles
      tags: dotfiles
    - name: led-heartbeat
      tags: led-heartbeat
    - name: unit-status-mail
      tags: unit-status-mail
