- hosts: raspberries
  become: true
  roles:
    - name: raspi-config
      tags: raspi-config
    - name: external-boot
      tags: external-boot
    - name: fstrim
      tags: fstrim
    - name: persistent-journal
      tags: persistent-journal
    - name: update
      tags: update
    - name: docker
      tags: docker
    - name: pivccu
      tags: pivccu
    - name: mqtt
      tags: mqtt
    - name: iobroker
      tags: iobroker
    - name: logger
      tags: logger
    - name: tools
      tags: tools
    - name: dotfiles
      tags: dotfiles
    - name: led-heartbeat
      tags: led-heartbeat
    - name: unit-status-mail
      tags: unit-status-mail
