- import_tasks: copy-templates.yml
  vars:
    directory: ../templates
    notify: Restart netdata service

- name: Symlink systemd unit file
  file:
    state: link
    src: "{{ root }}/netdata.service"
    path: /etc/systemd/system/{{ service_name }}.service
    force: true
  notify: Restart netdata service

- name: Start service
  systemd:
    state: started
    enabled: true
    name: "{{ service_name }}"
    daemon_reload: true
