- include: systemd-resolved-no-stub-resolver.yml

- import_tasks: copy-templates.yml
  vars:
    directory: ../templates
    notify: Restart adguard service

- name: Symlink systemd unit file
  ansible.builtin.file:
    state: link
    src: "{{ root }}/adguard.service"
    path: /etc/systemd/system/{{ service_name }}.service
    force: true
  notify: Restart adguard service

- name: Start service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ service_name }}"
    daemon_reload: true

- name: Install DNS utils
  ansible.builtin.apt:
    package: dnsutils
    state: present
