- include: systemd-resolved-no-stub-resolver.yml

- import_tasks: copy-templates.yml
  vars:
    directory: ../templates
    notify: Restart adguard service

- name: Install nftables
  ansible.builtin.apt:
    name: nftables
    state: latest

- name: Symlink nftables config file, disallowing DHCP to traverse the bridge
  ansible.builtin.file:
    state: link
    src: "{{ root }}/nftables.conf"
    path: /etc/nftables.conf
    force: true
    mode: '766'
    owner: root
    group: root

- name: Start nftables service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: nftables
    daemon_reload: true

- name: Symlink systemd unit file
  ansible.builtin.file:
    state: link
    src: "{{ root }}/adguard.service"
    path: /etc/systemd/system/{{ service_name }}.service
    force: true
  notify: Restart adguard service

- name: Start service
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: "{{ service_name }}"
    daemon_reload: true

- name: Install DNS utils
  ansible.builtin.apt:
    package: dnsutils
    state: present
